###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-09-19 11:53:50
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-09-19 11:54:12
###############################################################

invokables:
	institute_data_fieldset_form : Data/Form/InstituteDataFieldsetForm
	institute_data_create_form : Data/Form/InstituteDataCreateForm
	institute_data_edit_form : Data/Form/InstituteDataEditForm
	institute_data_search_form : Data/Form/InstituteDataSearchForm